builds:
  - binary: awsrole
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: awsrole
    homepage: https://github.com/toolschest/awsrole
    tap:
      owner: toolschest
      name: homebrew-toolschest
    commit_author:
      name: uzair_y3k
      email: uzair_y3k@live.com

checksum:
  name_template: 'checksums.txt'
